### ISSUE TITLE
Impossible de charger l'extension 'raepa' provoque une erreur lors de l'appel à sa méthode classFactory() 

### ISSUE THREAD

**Issue by triird** [3liz/qgis-raepa-plugin#73]
Bonjour, voici une erreur lors de l'exécution du plugin raepa :

```
Impossible de charger l'extension 'raepa' provoque une erreur lors de l'appel à sa méthode classFactory() 

ImportError: cannot import name 'postgis' from 'processing.tools' (C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python/plugins\processing\tools\__init__.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raepa\__init__.py", line 36, in classFactory
    from .raepa import Raepa
  File "C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raepa\raepa.py", line 22, in 
    from .processing.provider import RaepaProvider
  File "C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raepa\processing\provider.py", line 17, in 
    from .algorithms.get_downstream_route import GetDownstreamRoute
  File "C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raepa\processing\algorithms\get_downstream_route.py", line 20, in 
    from .get_data_as_layer import GetDataAsLayer
  File "C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\raepa\processing\algorithms\get_data_as_layer.py", line 21, in 
    from processing.tools import postgis
ImportError: cannot import name 'postgis' from 'processing.tools' (C:\PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python/plugins\processing\tools\__init__.py)


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.16.13-Hannover Hannover, a8618a94 

Chemin Python :
C:/PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python
C:/Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.16.13\bin\python39.zip
C:\PROGRA~1\QGIS31~1.13\apps\Python39\DLLs
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib
C:\Program Files\QGIS 3.16.13\bin
C:\PROGRA~1\QGIS31~1.13\apps\Python39
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\Pythonwin
C:/Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\tmasci\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users/tmasci/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\tmasci\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\tmasci\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
```

**Comment by Gustry** [comment]
C'est une erreur connue sur les dernières versions de QGIS. L'extension n'est pour le moment pas compatible >= 3.14.
Ticket déjà existant #41, je clos ce ticket.

Vous pouvez vous rapprocher de la société 3Liz pour du support sur l'extension et peut-être pouvoir financer la maintenance et l'ajout des dernières versions de QGIS Bureautique.

Cordialement

**Comment by triird** [comment]
Merci pour votre réponse
Bien cordialement,

**Comment by Gustry** [comment]
Cela doit être corrigé dans la version 0.5.0 https://github.com/3liz/qgis-raepa-plugin/releases/tag/0.5.0

Si vous utilisez le dépôt d'extension QGIS, il doit vous proposer la MAJ.
